import { Platform, StyleSheet } from 'react-native';

const isWeb = Platform.OS === 'web';

const styles = StyleSheet.create({
    card: {
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 20,
        marginBottom: 24,
        marginHorizontal: isWeb ? 8 : 4,
        marginTop: isWeb ? 8 : 12,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 8,
        position: 'relative',
        minWidth: isWeb ? 1200 : '100%',
        width: isWeb ? undefined : '100%',
        alignSelf: 'center',
        // Add a subtle background gradient effect for more depth
        ...(isWeb && {
            boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.08)',
        }),
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f5f5f5',
    },
    orderNumber: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#871919ff',
        textShadowColor: 'rgba(135, 25, 25, 0.1)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 1,
    },
    date: {
        fontSize: 12,
        color: '#666',
    },
    progressContainer: {
        marginBottom: 16,
    },
    statusText: {
        marginBottom: 4,
    },
    progressBackground: {
        height: 8,
        backgroundColor: '#f0f0f0',
        borderRadius: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 1,
        elevation: 1,
    },
    progressFill: {
        height: 8,
        borderRadius: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 1,
    },
    itemsContainer: {
        marginBottom: 16,
    },
    itemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    itemQuantity: {
        fontSize: 14,
        fontWeight: 'bold',
        width: 30,
        color: '#444',
    },
    itemName: {
        fontSize: 14,
        flex: 1,
        color: '#333',
    },
    itemPrice: {
        fontSize: 14,
        fontWeight: '500',
        color: '#333',
    },
    moreItems: {
        fontSize: 12,
        color: '#666',
        fontStyle: 'italic',
        marginTop: 4,
    },
    footer: {
        flexDirection: 'row',
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        paddingTop: 16,
        marginTop: 4,
        backgroundColor: '#fafafa',
        marginHorizontal: -20,
        marginBottom: -20,
        paddingHorizontal: 20,
        paddingBottom: 20,
        borderBottomLeftRadius: 16,
        borderBottomRightRadius: 16,
    },
    totalLabel: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    totalPrice: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#871919ff',
    },
    paymentBadge: {
        position: 'absolute',
        top: 20,
        right: 20,
        backgroundColor: '#f8d7da',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#f5c6cb',
    },
    paymentText: {
        color: '#721c24',
        fontSize: 10,
        fontWeight: 'bold',
    },
    addButton: {
        flex: 1,
        marginTop: 12,
        padding: 12,
        backgroundColor: "#4CAF50",
        borderRadius: 8,
        alignItems: "center",
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#45a049',
    },
    addButtonText: {
        color: "#fff",
        fontWeight: "bold",
    },
});

export default styles;