import { Platform, StyleSheet } from 'react-native';
const isWeb = Platform.OS === 'web';

const styles = StyleSheet.create({
    orderCard: {
        alignSelf: 'center',
        maxWidth: isWeb ? 1200 : '100%',
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        marginHorizontal: 8,
        marginTop: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        ...(isWeb && {
            '@media (max-width: 768px)': {
                padding: 16,
                marginHorizontal: 4,
                borderRadius: 12,
            },
            '@media (max-width: 480px)': {
                padding: 12,
                marginHorizontal: 0,
            },
        } as any),
    },
    orderHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    orderTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
        letterSpacing: -0.3,
        ...(isWeb && {
            '@media (max-width: 768px)': {
                fontSize: 16,
            },
        } as any),
    },
    orderDate: {
        fontSize: 13,
        color: '#6b7280',
        marginTop: 4,
        fontWeight: '500',
        ...(isWeb && {
            '@media (max-width: 768px)': {
                fontSize: 12,
            },
        } as any),
    },
    orderStatus: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        overflow: 'hidden',
        textAlign: 'center',
        minWidth: 80,
        marginBottom: 0,
    },
    paymentStatus: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        overflow: 'hidden',
        textAlign: 'center',
        minWidth: 80,
    },
    statusLabel: {
        fontSize: 10,
        color: '#9ca3af',
        fontWeight: '500',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    paymentLabel: {
        fontSize: 10,
        color: '#9ca3af',
        fontWeight: '500',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    statusCompleted: {
        color: '#059669',
        backgroundColor: '#d1fae5',
    },
    statusInProgress: {
        color: '#2563eb',
        backgroundColor: '#dbeafe',
    },
    statusCanceled: {
        color: '#dc2626',
        backgroundColor: '#fee2e2',
    },
    statusPending: {
        color: '#d97706',
        backgroundColor: '#fef3c7',
    },
    divider: {
        height: 1,
        backgroundColor: '#f3f4f6',
        marginVertical: 12,
    },
    userInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
        paddingVertical: 4,
    },
    infoIconContainer: {
        marginRight: 10,
        width: 20,
        alignItems: 'center',
    },
    infoText: {
        fontSize: 14,
        color: '#374151',
        fontWeight: '500',
    },
    sectionTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 10,
        marginTop: 4,
    },
    itemsList: {
        marginBottom: 16,
    },
    orderItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: '#f9fafb',
        borderRadius: 10,
        marginBottom: 6,
    },
    itemName: {
        fontSize: 15,
        fontWeight: '500',
        color: '#374151',
        flex: 1,
    },
    itemCount: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
        marginLeft: 8,
        marginRight: 8,
    },
    orderTotal: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#f9fafb',
        borderRadius: 10,
        marginVertical: 12,
    },
    totalLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
    },
    totalPrice: {
        fontSize: 20,
        fontWeight: '700',
        color: '#871919ff',
        letterSpacing: -0.3,
    },
    orderTimes: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#f3f4f6',
    },
    timeInfo: {
        fontSize: 12,
        color: '#6b7280',
        fontWeight: '500',
    },
    emptyMessage: {
        padding: 15,
        textAlign: 'center',
        color: '#9ca3af',
        fontFamily: 'Helvetica',
        fontSize: 14,
    },
});

export default styles;