import { Platform, StyleSheet } from 'react-native';
const isWeb = Platform.OS === 'web';

const styles = StyleSheet.create({
    card: {
        alignSelf: "center",
        minWidth: isWeb ? 1200 : "100%",
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        marginHorizontal: 8,
        marginTop: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    orderNumber: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
        letterSpacing: -0.3,
    },
    status: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        overflow: 'hidden',
        textAlign: 'center',
        minWidth: 80,
    },
    pending: {
        color: '#d97706',
        backgroundColor: '#fef3c7',
    },
    completed: {
        color: '#059669',
        backgroundColor: '#d1fae5',
    },
    inProgress: {
        color: '#2563eb',
        backgroundColor: '#dbeafe',
    },
    cancelled: {
        color: '#dc2626',
        backgroundColor: '#fee2e2',
    },
    paid: {
        color: '#059669',
        backgroundColor: '#d1fae5',
    },
    items: {
        marginBottom: 16,
    },
    itemText: {
        fontSize: 15,
        color: '#4b5563',
        lineHeight: 22,
        marginBottom: 4,
    },
    itemContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: '#f9fafb',
        borderRadius: 10,
        marginBottom: 6,
    },
    itemName: {
        fontSize: 15,
        fontWeight: '500',
        color: '#374151',
        flex: 1,
    },
    itemQuantity: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
        marginRight: 8,
    },
    itemPrice: {
        fontSize: 15,
        fontWeight: '600',
        color: '#871919ff',
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#f3f4f6',
    },
    totalPrice: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1f2937',
        letterSpacing: -0.3,
    },
    paymentStatus: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        overflow: 'hidden',
        textAlign: 'center',
        minWidth: 80,
    },
    totalLabel: {
        fontSize: 14,
        color: '#6b7280',
        fontWeight: '500',
        marginBottom: 4,
    },
    totalContainer: {
        alignItems: 'flex-start',
    },
    statusContainer: {
        alignItems: 'center',
    },
    statusLabel: {
        fontSize: 10,
        color: '#9ca3af',
        fontWeight: '500',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    paymentContainer: {
        alignItems: 'center',
    },
    paymentLabel: {
        fontSize: 10,
        color: '#9ca3af',
        fontWeight: '500',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
});

export default styles;