import { Platform, StyleSheet } from 'react-native';

const isWeb = Platform.OS === 'web';
const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignSelf: 'center',
        minWidth: "100%",
    },
    analyticsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 15,
        paddingHorizontal: 10,
        backgroundColor: '#f7f7f7',
        borderRadius: 8,
        marginVertical: 10,
    },
    analyticsItem: {
        alignItems: 'center',
        flex: 1,
    },
    analyticsValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#871919ff',
        marginBottom: 5,
    },
    analyticsLabel: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
    },
    // Dashboard overview styles
    dashboardContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    metricCard: {
        backgroundColor: 'white',
        borderRadius: 10,
        padding: 15,
        alignItems: 'center',
        flex: 1,
        margin: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 3,
    },
    metricValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginVertical: 8,
    },
    metricLabel: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
    },
    metricTrend: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#4CAF50',
        marginTop: 5,
    },
    // Card styles
    card: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 15,
        marginBottom: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        marginBottom: 15,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        marginLeft: 10,
        flex: 1,
    },
    cardPeriod: {
        fontSize: 12,
        color: '#666',
        alignSelf: 'center',
    },
    // Menu item analytics
    menuItemAnalytics: {
        marginTop: 5,
        marginBottom: 15,
    },
    menuItemAnalyticsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 10,
        borderBottomWidth: 2,
        borderBottomColor: '#e0e0e0',
        marginBottom: 5,
    },
    menuItemAnalyticsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    menuItemAnalyticsName: {
        flex: 2,
        fontSize: 14,
        color: '#333',
        fontWeight: '500',
    },
    menuItemCount: {
        flex: 1,
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
    },
    menuItemRevenue: {
        flex: 1,
        fontSize: 14,
        color: '#871919ff',
        fontWeight: '600',
        textAlign: 'right',
    },
    // Period selector styles
    periodSelector: {
        flexDirection: 'row',
        marginBottom: 15,
        borderRadius: 8,
        overflow: 'hidden',
        backgroundColor: '#f0f0f0',
        marginHorizontal: 5,
    },
    periodTab: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
    },
    periodTabActive: {
        backgroundColor: '#871919ff',
    },
    periodTabText: {
        fontSize: 14,
        color: '#333',
    },
    periodTabTextActive: {
        fontSize: 14,
        color: '#fff',
        fontWeight: '600',
    },
    periodLabel: {
        fontSize: 14,
        color: '#666',
        fontWeight: 'normal',
    },
    // Reports styles
    reportsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: 10,
        marginBottom: 20,
    },
    reportButton: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f7f7f7',
        borderRadius: 10,
        padding: 16,
        width: '48%',
        marginBottom: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 1,
        elevation: 1,
    },
    reportButtonText: {
        fontSize: 14,
        color: '#333',
        marginTop: 8,
        fontWeight: '500',
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#871919ff',
        marginBottom: 10,
        marginTop: 15,
        fontFamily: 'Helvetica',
    },
    buttonSecondary: {
        backgroundColor: '#e8e8e8ff',
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 10,
    },
    buttonTextSecondary: {
        color: '#333',
        fontSize: 16,
        fontWeight: '500',
    },
});

export default styles;