import { Platform, StyleSheet } from 'react-native';
const isWeb = Platform.OS === 'web';


const styles = (isCartPaused: boolean) => StyleSheet.create({
    container: { 
        flex: 1,
        padding: 20,
        backgroundColor: '#ffffffff',
        borderWidth: 1,
        ...(isWeb && {
            '@media (max-width: 768px)': {
                padding: 16,
            },
        } as any),
    },
    header: {
        marginTop: 30,
        marginBottom: "1%",
        flexDirection: 'row',
        alignItems: 'center',
        gap: 20,
        ...(isWeb && {
            '@media (max-width: 768px)': {
                gap: 12,
                marginTop: 20,
            },
        } as any),
    },
    headerTitle: {
        fontSize: 24,
        marginTop: 20,
        marginBottom: 10,
        color: '#871919ff',
        fontWeight: 'bold',
        fontFamily: 'Helvetica',
        ...(isWeb && {
            '@media (max-width: 768px)': {
                fontSize: 20,
                marginTop: 16,
            },
        } as any),
    },
    backButton: { 
        backgroundColor: '#e8e8e8ff', 
        width: 50, 
        height: 50, 
        borderRadius: 25, 
        justifyContent: 'center', 
        alignItems: 'center' 
    },
    checkoutButton: { 
        backgroundColor: isCartPaused ? '#a9a9a9ff' : '#871919ff', 
        marginTop: 8, 
        height: 58, 
        borderRadius: 30, 
        justifyContent: 'center', 
        alignItems: 'center',
        shadowColor: '#871919',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: isCartPaused ? 0 : 0.3,
        shadowRadius: 8,
        elevation: isCartPaused ? 0 : 4,
    },
    summary: {
        flexDirection: 'column',
        gap: 12,
        marginBottom: 20,
        backgroundColor: '#ffffff',
        padding: 20,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 2,
    },
    summaryHeader: {
        marginBottom: 4,
    },
    summaryTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1a1a1a',
        fontFamily: 'Helvetica',
    },
    summaryLabel: {
        fontSize: 14,
        color: '#666',
        fontFamily: 'Helvetica',
    },
    summaryValue: {
        fontSize: 14,
        color: '#333',
        fontFamily: 'Helvetica',
        fontWeight: '500',
    },
    summaryDivider: {
        height: 1,
        backgroundColor: '#e0e0e0',
        marginVertical: 4,
    },
    totalLabel: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1a1a1a',
        fontFamily: 'Helvetica',
    },
    totalValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#871919ff',
        fontFamily: 'Helvetica',
    },
    summaryColumn: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    checkoutContainer: {
        maxWidth: isWeb ? 1200 : "100%",
        width: '100%',
        alignSelf: 'center',
        marginTop: 20,
        marginBottom: 20, 
        flexDirection: 'column', 
        gap: 16,
        paddingHorizontal: isWeb ? 0 : 16,
        ...(isWeb && {
            '@media (max-width: 768px)': {
                marginTop: 16,
                marginBottom: 16,
                gap: 12,
            },
        } as any),
    },
    menuItemContainer: {
        flexDirection: 'row',
        alignItems: 'stretch',
        minHeight: 140,
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        shadowColor: '#871919',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
        borderWidth: 0,
    },
    menuItemImageWrapper: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    menuItemImageContainer: {
        width: 90,
        height: 90,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 16,
        overflow: 'hidden',
        backgroundColor: '#f8f8f8',
    },
    menuItemDetailsContainer: {
        paddingLeft: 16,
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'space-between',
        gap: 10,
    },
    menuItemHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    menuItemTitleSection: {
        flex: 1,
        marginRight: 12,
    },
    menuItemNameText: {
        fontFamily: 'Helvetica',
        fontWeight: 'bold',
        fontSize: 17,
        color: '#1a1a1a',
        marginBottom: 4,
    },
    basePriceText: {
        fontFamily: 'Helvetica',
        fontSize: 13,
        color: '#888',
    },
    totalPriceContainer: {
        backgroundColor: '#fff5f5',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 10,
    },
    menuItemTotalPrice: {
        fontFamily: 'Helvetica',
        fontWeight: 'bold',
        fontSize: 18,
        color: '#871919ff',
    },
    sidesContainer: {
        backgroundColor: '#fafafa',
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    sidesLabel: {
        fontFamily: 'Helvetica',
        fontSize: 11,
        fontWeight: '600',
        color: '#871919ff',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 6,
    },
    sideRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 4,
    },
    sideInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    sideDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#871919ff',
        marginRight: 8,
    },
    sideName: {
        fontFamily: 'Helvetica',
        fontSize: 14,
        color: '#444',
        flex: 1,
    },
    sidePrice: {
        fontFamily: 'Helvetica',
        fontSize: 13,
        color: '#666',
        fontWeight: '500',
        marginRight: 8,
    },
    removeSideButton: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: '#ccc',
        justifyContent: 'center',
        alignItems: 'center',
    },
    quantityControlsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        marginTop: 4,
    },
    quantityControls: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    minusButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#871919ff',
        justifyContent: 'center',
        alignItems: 'center',
    },
    plusButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#871919ff',
        justifyContent: 'center',
        alignItems: 'center',
    },
    quantityBadge: {
        minWidth: 32,
        height: 32,
        borderRadius: 8,
        backgroundColor: '#f5f5f5',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    quantityText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1a1a1a',
    },
    menuItemPriceContainer: {
        justifyContent: 'flex-start',
        paddingTop: 2,
        minWidth: 70,
        alignItems: 'flex-end',
    },
    quantityPriceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 8,
        maxWidth: 200,
    },
    menuItemImage: {
        width: "100%",
        height: "100%",
        borderRadius: 12,
        resizeMode: 'cover',
    },
    menuItemName: {
        justifyContent: 'center',
        flex: 1,
    },
    menuItemTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 4,
    },
    quantityText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        minWidth: 24,
        textAlign: 'center',
    },
    buttonText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#6c757d',
        lineHeight: 18,
    },
    quantityPrice: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        backgroundColor: '#ffffff',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#e9ecef',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 1,
    },
    price: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#871919ff',
        textAlign: 'right',
    },
    plusMinusButton: {
        backgroundColor: '#871919ff', 
        width: 32, 
        height: 32,
        borderRadius: 8, 
        justifyContent: 'center', 
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: '#e9ecef',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 2,
        elevation: 1,
    },
    enterBoxStyle: {
        backgroundColor: "#53c851",
        color: "white",
        textAlign: "center",
        textAlignVertical: "center",
        fontSize: 20,
        height: 35,
        width: "auto",
        borderRadius: 20,
    },
    picker: {
        borderWidth: 2,
        height: 50,
        width: 150,
        marginLeft: 10,
    },
    textBox: {
        marginLeft: 15,
        borderWidth: 2,
        width: 50,
        height: 50,
        alignSelf: "center",
    },
    tableNum: {
        fontSize: 30,
    },
    tableBox: {
        flexDirection: 'row',
    },
    enterBox: {
        marginTop: 30,
        width: 350,
    },
    box: {
        padding: 20,
        borderRadius: 8,
    },
    title: {
        textAlign: "center",
        fontSize: 60,
        fontWeight: 'bold',
        alignItems: "center",
        color: '#000',
    },
    center: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    waitressContainer: {
        flex: 1,
        alignItems: 'center',
        paddingTop: 20,
    },
    waitressTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#871919ff',
        marginBottom: 30,
        fontFamily: 'Helvetica',
    },
    tableLayout: {
        width: '100%',
        marginVertical: 20,
        alignItems: 'center',
    },
    tableRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginBottom: 15,
    },
    tableButton: {
        width: 70,
        height: 70,
        borderRadius: 10,
        backgroundColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 10,
        borderWidth: 1,
        borderColor: '#d0d0d0',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    selectedTableButton: {
        backgroundColor: '#871919ff',
        borderColor: '#700000',
    },
    tableButtonText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
    },
    selectedTableText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        marginTop: 15,
    },
    selectedTableInfo: {
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    takeOrderButton: {
        backgroundColor: '#871919ff',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 60,
        width: 220,
        borderRadius: 30,
        marginTop: 20,
    },
    disabledButton: {
        backgroundColor: '#cccccc',
    },
    buttonIcon: {
        marginRight: 10,
    },
    takeOrderButtonText: {
        color: '#ffffff',
        fontWeight: 'bold',
        fontSize: 18,
    },
    tableNumber: {
        fontSize: 28,
        fontWeight: '900',
        color: '#871919ff',
        letterSpacing: 0.5,
        textShadowColor: 'rgba(135, 25, 25, 0.2)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    headerInfo: {
        flexDirection: 'column',
        justifyContent: 'center',
        marginLeft: 5,
    },
});

export default styles;