import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  loadingMore: {
    padding: 20,
    alignItems: 'center',
  },
  loadingMoreText: {
    color: '#666',
    fontSize: 14,
    marginTop: 5,
  },
  container: { 
    flex: 1,
    padding: 20,
    backgroundColor: '#ffffffff'
  },
  header: {
    marginBottom: "5%",
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  // Overlay for darkening the background when sheet is open
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 1,
  },
  // Bottom Sheet Styles
  bottomSheet: {
    zIndex: 2,
  },
  bottomSheetContent: {
    flex: 1,
    padding: 20,
    paddingBottom: "25%",
  },
  bottomSheetTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#871919ff',
    marginBottom: 30,
    textAlign: 'center',
    fontFamily: 'Helvetica',
  },
  formGroup: {
    marginBottom: 15,
  },
  input: {
    backgroundColor: '#e8e8e8ff',
    borderRadius: 30,
    padding: 15,
    fontSize: 16,
    height: 58,
    marginBottom: 15,
  },
  textArea: {
    height: 120,
    textAlignVertical: 'top',
    paddingTop: 15,
  },
  buttonContainer: {
    flexDirection: 'column',
    marginTop: 20,
    gap: 15,
  },
  submitButton: {
    backgroundColor: '#871919ff',
    height: 58, 
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  cancelButton: {
    backgroundColor: '#e8e8e8ff',
    height: 58, 
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#333',
    fontSize: 16,
    fontWeight: '500',
  },
  headerTitle: {
    flex: 1,
    fontSize: 24,
    color: '#871919ff',
    fontWeight: 'bold',
    fontFamily: 'Helvetica',
  },
  backButton: { 
    backgroundColor: '#e8e8e8ff', 
    width: 50, 
    height: 50, 
    borderRadius: 25, 
    justifyContent: 'center', 
    alignItems: 'center' 
  },
  sendButton: {
    backgroundColor: '#871919ff',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  filterContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  filterTab: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: '#f0f0f0',
    minWidth: 70,
    alignItems: 'center',
  },
  activeFilterTab: {
    backgroundColor: '#871919ff',
  },
  filterTabText: {
    color: '#333',
    fontWeight: '500',
  },
  activeFilterTabText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  notificationCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 15,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    position: 'relative',
  },
  unreadCard: {
    backgroundColor: '#fff9f9',
    borderLeftWidth: 3,
    borderLeftColor: '#871919ff',
  },
  unreadIndicator: {
    position: 'absolute',
    top: 15,
    right: 15,
    width: 8,
    height: 8,
    backgroundColor: '#871919ff',
    borderRadius: 4,
  },
  notificationTitle: { 
    fontSize: 16, 
    fontWeight: 'bold',
    color: '#333333',
  },
  notificationMessage: { 
    fontSize: 14, 
    marginTop: 4,
    color: '#555555',
  },
  notificationTimestamp: { 
    fontSize: 12, 
    color: '#888888', 
    marginTop: 8,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyMessage: {
    marginTop: 10,
    textAlign: 'center',
    fontSize: 16,
    color: '#7e7d7dff',
    fontWeight: 'bold',
    fontFamily: 'Helvetica',
  },
  center: { 
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center' 
  },
  loadingText: {
    marginTop: 10,
    color: '#666',
    fontSize: 14,
  },
  // Web-specific styles
  webHeader: {
    marginTop: 20,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  webHeaderTitle: {
    fontSize: 32,
    color: '#871919ff',
    fontWeight: 'bold',
    fontFamily: 'Helvetica',
  },
  webAddButton: {
    backgroundColor: '#871919ff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 6,
    marginLeft: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  webAddButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  webModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  webModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 30,
    width: '100%',
    maxWidth: 500,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  webModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#871919ff',
    marginBottom: 25,
    textAlign: 'center',
    fontFamily: 'Helvetica',
  },
  webFormGroup: {
    marginBottom: 20,
  },
  webInput: {
    backgroundColor: '#f8f8f8',
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    minHeight: 50,
  },
  webTextArea: {
    minHeight: 120,
    textAlignVertical: 'top',
    paddingTop: 15,
  },
  webButtonContainer: {
    flexDirection: 'row',
    gap: 15,
    marginTop: 20,
  },
  webSubmitButton: {
    backgroundColor: '#871919ff',
    flex: 1,
    paddingVertical: 15,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  webSubmitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  webCancelButton: {
    backgroundColor: '#f0f0f0',
    flex: 1,
    paddingVertical: 15,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  webCancelButtonText: {
    color: '#333',
    fontSize: 16,
    fontWeight: '500',
  },
});

export default styles;