import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    scrollContainer: {
        flex: 1,
        backgroundColor: '#f8f8f8',
        paddingHorizontal: 18,
    },
    centeredContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    viewMoreButton: {
        marginTop: 10,
        marginBottom: 5,
        borderColor: '#871919ff',
        borderRadius: 25,
        alignSelf: 'center',
        width: '50%',
    },
    profileCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 18,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    profileTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#871919ff',
        marginBottom: 10,
        fontFamily: 'Helvetica',
    },
    profileDetail: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        marginBottom: 8,
    },
    profileIcon: {
        marginRight: 12,
        marginTop: 3,
    },
    profileLabel: {
        fontWeight: 'bold',
        color: '#871919ff',
        fontSize: 14,
        marginBottom: 2,
    },
    profileValue: {
        fontSize: 16,
        color: '#333',
    },
    sectionCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 18,
        marginBottom: 18,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 2,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#871919ff',
        marginBottom: 10,
        fontFamily: 'Helvetica',
    },
    roleButtonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 15,
        marginTop: 5,
    },
    roleButton: {
        flex: 1,
        marginHorizontal: 4,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#871919ff',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    activeRoleButton: {
        backgroundColor: '#871919ff',
    },
    buttonPrimary: {
        backgroundColor: '#871919ff',
        borderRadius: 25,
        marginTop: 12,
        marginBottom: 2,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 3,
    },
    disabledButton: {
        backgroundColor: '#D3D3D3',
        opacity: 0.8,
        elevation: 1,
    },
    orderCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#e5e5e5',
    },
    orderId: {
        fontWeight: '700',
        fontSize: 17,
        marginBottom: 12,
        color: '#871919ff',
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    orderLabel: {
        fontWeight: '700',
        marginTop: 8,
        color: '#333',
        fontSize: 15,
    },
    orderValue: {
        fontWeight: '400',
        color: '#333',
    },
    orderItemsList: {
        marginLeft: 12,
        marginVertical: 8,
        backgroundColor: '#f9f9f9',
        borderRadius: 8,
        padding: 8,
    },
    orderItemText: {
        fontSize: 15,
        color: '#333',
        paddingVertical: 3,
    },
    orderItemCount: {
        color: '#871919ff',
        fontSize: 14,
        fontWeight: '600',
    },
    orderNoItems: {
        marginLeft: 12,
        fontStyle: 'italic',
        color: '#888',
        marginVertical: 8,
    },
    timeSection: {
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
    },
    priceText: {
        fontWeight: '600',
        fontSize: 16,
        color: '#871919ff',
    },
    pendingText: {
        color: '#e69500',
        fontStyle: 'italic',
    },
    emptyMessage: {
        textAlign: 'center',
        color: '#7e7d7dff',
        fontFamily: 'Helvetica',
        fontSize: 16,
        marginVertical: 10,
        maxWidth: '80%',
    },
    loadingContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    loadingText: {
        marginTop: 15,
        fontSize: 16,
        color: '#666',
        fontFamily: 'Helvetica',
    },
    errorContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        width: '100%',
    },
    errorTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#871919ff',
        marginVertical: 10,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: "5%",
        flexDirection: 'row',
        alignItems: 'center',
        gap: 20,
    },
    headerTitle: {
        fontSize: 24,
        color: '#871919ff',
        fontWeight: 'bold',
        fontFamily: 'Helvetica',
    },
    backButton: {
        backgroundColor: '#e8e8e8ff', 
        width: 50, 
        height: 50, 
        borderRadius: 25, 
        justifyContent: 'center', 
        alignItems: 'center' 
    },
});

export default styles;