import { Platform, StyleSheet } from 'react-native';
const isWeb = Platform.OS === 'web';

const styles = StyleSheet.create({
    container: { 
        flex: 1,
        padding: 20,
        backgroundColor: '#ffffffff',
        borderWidth: 1,
    },
    header: {
        marginTop: 30,
        marginBottom: "1%",
        flexDirection: 'row',
        alignItems: 'center',
        gap: 20,
    },
    headerTitle: {
        fontSize: 24,
        marginTop: 20,
        marginBottom: 10,
        color: '#871919ff',
        fontWeight: 'bold',
        fontFamily: 'Helvetica',
    },
    backButton: { 
        backgroundColor: '#e8e8e8ff', 
        width: 50, 
        height: 50, 
        borderRadius: 25, 
        justifyContent: 'center', 
        alignItems: 'center' 
    },
    checkoutButton: { 
        backgroundColor: '#871919ff', 
        marginTop: 20, 
        height: 58, 
        borderRadius: 30, 
        justifyContent: 'center', 
        alignItems: 'center'
    },
    summary: {
        flexDirection: 'column',
        gap: 10,
        marginBottom: 20,
        backgroundColor: '#F0F0F0',
        padding: 20,
        borderRadius: 10,
    },
    summaryColumn: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    checkoutContainer: {
      minWidth: isWeb ? 1200 : "100%",
      alignSelf: 'center',
      marginBottom: 20, 
      flexDirection: 'column', 
      gap: 10 
    },
    menuItemContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        height: 100,
        paddingHorizontal: 20,
        paddingVertical: 12,
        backgroundColor: '#ffffff',
        borderRadius: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    menuItemImageContainer: {
      width: 70,
      height: 70,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: '#f8f8f8',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    menuItemDetailsContainer: {
      paddingLeft: 16,
      flex: 1,
      flexDirection: 'column',
      height: "100%",
      justifyContent: 'space-between',
    },
    menuItemPriceContainer: {
      height: "100%",
      justifyContent: 'center',
      width: 55,
    },
    quantityPriceContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 8,
      maxWidth: 200,
    },
    menuItemImage: {
      width: "100%",
      height: "100%",
      borderRadius: 12,
      resizeMode: 'cover',
    },
    menuItemName: {
      justifyContent: 'center',
      flex: 1,
    },
    menuItemTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
      marginBottom: 4,
    },
    quantityText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#495057',
      minWidth: 24,
      textAlign: 'center',
    },
    buttonText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#6c757d',
      lineHeight: 18,
    },
    quantityPrice: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      backgroundColor: '#ffffff',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: '#e9ecef',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 3,
      elevation: 1,
    },
    price: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#871919ff',
      textAlign: 'right',
    },
    plusMinusButton: {
      backgroundColor: '#871919ff', 
      width: 32, 
      height: 32,
      borderRadius: 8, 
      justifyContent: 'center', 
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: '#e9ecef',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation: 1,
    },
    enterBoxStyle: {
        backgroundColor: "#53c851",
        color: "white",
        textAlign: "center",
        textAlignVertical: "center",
        fontSize: 20,
        height: 35,
        width: "auto",
        borderRadius: 20,
    },
    picker: {
        borderWidth: 2,
        height: 50,
        width: 150,
        marginLeft: 10,
    },
    textBox: {
        marginLeft: 15,
        borderWidth: 2,
        width: 50,
        height: 50,
        alignSelf: "center",
    },
    tableNum: {
        fontSize: 30,
    },
    tableBox: {
        flexDirection: 'row',
    },
    enterBox: {
        marginTop: 30,
        width: 350,
    },
    box: {
        padding: 20,
        borderRadius: 8,
    },
    title: {
        textAlign: "center",
        fontSize: 60,
        fontWeight: 'bold',
        alignItems: "center"
    },
    center: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    waitressContainer: {
      flex: 1,
      alignItems: 'center',
      paddingTop: 20,
    },
    waitressTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#871919ff',
      marginBottom: 30,
      fontFamily: 'Helvetica',
    },
    tableLayout: {
      width: '100%',
      marginVertical: 20,
      alignItems: 'center',
    },
    tableRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 15,
    },
    tableButton: {
      width: 70,
      height: 70,
      borderRadius: 10,
      backgroundColor: '#f0f0f0',
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 10,
      borderWidth: 1,
      borderColor: '#d0d0d0',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
    },
    selectedTableButton: {
      backgroundColor: '#871919ff',
      borderColor: '#700000',
    },
    tableButtonText: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#333',
    },
    selectedTableText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
      marginTop: 15,
    },
    selectedTableInfo: {
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
    },
    takeOrderButton: {
      backgroundColor: '#871919ff',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 60,
      width: 220,
      borderRadius: 30,
      marginTop: 20,
    },
    disabledButton: {
      backgroundColor: '#cccccc',
    },
    buttonIcon: {
      marginRight: 10,
    },
    takeOrderButtonText: {
      color: '#ffffff',
      fontWeight: 'bold',
      fontSize: 18,
    },
    tableNumber: {
      fontSize: 28,
      fontWeight: '900',
      color: '#871919ff',
      letterSpacing: 0.5,
      textShadowColor: 'rgba(135, 25, 25, 0.2)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    headerInfo: {
      flexDirection: 'column',
      justifyContent: 'center',
      marginLeft: 5,
    },
});

export default styles;